# ****************************************************************************
# NOTES:
#
# This is an example of a production deployment that uses GitHub Pages along
# with a second "production" GitHub organisation. If you prefer to implement
# your own workflow, or do not need production deployments, then you should
# delete this file.
#
# In order for this to work, you must replace PRODUCTION_ORGANISATION below
# with the name of your production GitHub organisation, under REPOSITORY_NAME.
#
# For example, if your production organisation is "my-stats-org", then use:
#
# REPOSITORY_NAME: my-stats-org/my-stats-org.github.io
#
# ****************************************************************************

name: Deploy to production

on:
  push:
    branches:
      - master
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.10
    - name: Build the site
      run: |
        gem install bundler -v 2.4.22
        bundle config path vendor/bundle
        bundle install
        bundle exec jekyll build --config _config.yml,_config_prod.yml
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        repository-name: sdgtk/sdgtk.github.io
        token: ${{ github.event_name == 'schedule' && secrets.GITHUB_TOKEN || secrets.token }}
        branch: master
        folder: _site
        clean: true